// DO NOT EDIT THIS FILE
// Until n unless it is necessary.
const moment = require('moment-timezone')

// Audit Event Class
const AuditEvent = class {
  constructor (data, options) {
    // If data is not passed, throw an error.
    if (!data) throw new Error('No data Passed')

    // If data type is incorrect, throw an error.
    if (data.type !== 'audit_events') throw new Error('Not an Audit Event passed.\n' + JSON.stringify(data))

    // If data attributes is not available, throw an error.
    if (!data.attributes) throw new Error('No Attributes Data passed.')

    // Now everything is validated, start processing data.
    const attributes = data.attributes
    let auditEventType
    if (attributes && attributes.type_of && Object.getPrototypeOf(attributes.type_of) === String.prototype) {
      auditEventType = attributes.type_of.split('.')
    } else {
      throw new Error('Audit Event Type not passed.\n' + JSON.stringify(attributes))
    }
    this.componentType = auditEventType[0]
    this.eventType = auditEventType[1]

    // Extract Username and email from AuditEvent
    this.userName = attributes.attributed_to_display_name
    this.userEmail = attributes.attributed_to_email

    // Extract Component Name
    this.componentName = attributes.display_name

    // Extract Timestamp
    this.when = new Date(attributes.updated_at)

    // Extract Property Name
    if (data.meta && data.meta.property_name) {
      this.propertyName = data.meta.property_name
    }

    // Extract Launch Event Details
    this.eventDetails = new LaunchEvent(attributes.entity)
    this.attributes = attributes
    this.raw = data

    // Convert TimeStamp to another TZ provided in configuration.
    if (options && options.tz) {
      this.when = moment(this.when).tz(options.tz)
    }
    // Extract Property Id
    if (data.relationships && data.relationships.property && data.relationships.property.data && data.relationships.property.data.id) {
      this.propertyId = data.relationships.property.data.id
    }

    // Branding!
    if (options.poweredBy) this.poweredBy = options.poweredBy

    // Add Email Address and User Name from Audit Event.
    this.who = { email: this.userEmail, name: this.userName }
  }

  get componentType () { return this._componentType }
  set componentType (val) { if (COMPONENT_TYPES[val.toUpperCase()]) this._componentType = val }

  get eventType () { return this._eventType }
  set eventType (val) { if (EVENT_TYPES[val.toUpperCase()]) this._eventType = val }

  get about () {
    return {
      componentType: this.componentType,
      componentName: this.componentName,
      propertyName: this.propertyName,
      eventType: this.eventType,
      when: this.when,
      who: { name: this.userName, email: this.userEmail },
      eventDetails: this.eventDetails,
      poweredBy: this.poweredBy
    }
  }
}

const COMPONENT_TYPES = {
  PROPERTY: 'property',
  EXTENSION: 'extension',
  DATA_ELEMENT: 'data_element',
  RULE: 'rule',
  RULE_COMPONENT: 'rule_component',
  LIBRARY: 'library',
  BUILD: 'build',
  ENVIRONMENT: 'environment',
  HOST: 'host'
}

const EVENT_TYPES = {
  CREATED: 'created',
  UPDATED: 'updated',
  DELETED: 'deleted'
}

// LaunchEvent Class
const LaunchEvent = class {
  constructor (data) {
    if (!data) throw new Error('No data Passed.')
    if (Object.getPrototypeOf(data) === String.prototype) {
      data = JSON.parse(data)
    }
    data = data.data
    if (!data.attributes) throw new Error('Attributes not found in event.\n' + JSON.stringify(data))
    this.componentName = data.attributes.name
    this.when = new Date(data.attributes.updated_at)
    this.attributes = data.attributes
    this.raw = data
  }
}

module.exports = { LaunchEvent, AuditEvent }
